import type { SkillCategory } from "./skills";

export const skillCategories: SkillCategory[] = [
  {
    id: 'frontend',
    title: 'Frontend Development',
    subtitle: 'Engineering the web layer',
    accent: 'sky',
    accentHex: '#0ea5e9',
    bgFrom: 'from-sky-950/80',
    bgTo: 'to-slate-900/90',
    borderColor: 'border-sky-500/20',
    icon: '⟨/⟩',
    skills: [
      { name: 'HTML',              icon: '/html5.png',       useImage: true,  level: 'expert'       },
      { name: 'CSS',               icon: '/css.png',         useImage: true,  level: 'expert'       },
      { name: 'JavaScript',        icon: '/javascript.png',  useImage: true,  level: 'expert'       },
      { name: 'TypeScript',        icon: '/tsx.jpg',         useImage: true,  level: 'advanced'     },
      { name: 'React',             icon: '/react.png',       useImage: true,  level: 'expert'       },
      { name: 'Next.js',           icon: '/next.png',        useImage: true,  level: 'advanced'     },
      { name: 'Tailwind CSS',      icon: '🎨',               useImage: false, level: 'expert'       },
      { name: 'Responsive Design', icon: '📱',               useImage: false, level: 'expert'       },
      { name: 'Git & GitHub',      icon: '🌿',               useImage: false, level: 'advanced'     },
    ],
  },
  {
    id: 'data',
    title: 'Data & Productivity',
    subtitle: 'Analysis, reporting & tooling',
    accent: 'emerald',
    accentHex: '#10b981',
    bgFrom: 'from-emerald-950/80',
    bgTo: 'to-slate-900/90',
    borderColor: 'border-emerald-500/20',
    icon: '📊',
    skills: [
      { name: 'Microsoft Excel',  icon: '📗', useImage: false, level: 'advanced'     },
      { name: 'Microsoft Word',   icon: '📘', useImage: false, level: 'expert'       },
      { name: 'Power BI',         icon: '📊', useImage: false, level: 'intermediate' },
      { name: 'SharePoint',       icon: '🗂️', useImage: false, level: 'intermediate' },
    ],
  },
  {
    id: 'admin',
    title: 'Administrative & HR',
    subtitle: 'People, process & operations',
    accent: 'violet',
    accentHex: '#8b5cf6',
    bgFrom: 'from-violet-950/80',
    bgTo: 'to-slate-900/90',
    borderColor: 'border-violet-500/20',
    icon: '🏛️',
    skills: [
      { name: 'HR Support',           icon: '🤝', useImage: false, level: 'advanced'     },
      { name: 'Org. Management',      icon: '🏗️', useImage: false, level: 'advanced'     },
      { name: 'Documentation',        icon: '📋', useImage: false, level: 'expert'       },
      { name: 'Team Coordination',    icon: '👥', useImage: false, level: 'advanced'     },
    ],
  },
  {
    id: 'core',
    title: 'Core Professional',
    subtitle: 'Mindset, craft & character',
    accent: 'amber',
    accentHex: '#f59e0b',
    bgFrom: 'from-amber-950/80',
    bgTo: 'to-slate-900/90',
    borderColor: 'border-amber-500/20',
    icon: '⚡',
    skills: [
      { name: 'Communication',    icon: '💬', useImage: false, level: 'expert'   },
      { name: 'Adaptability',     icon: '🔄', useImage: false, level: 'expert'   },
      { name: 'Problem-Solving',  icon: '🧩', useImage: false, level: 'expert'   },
      { name: 'Leadership',       icon: '🎯', useImage: false, level: 'advanced' },
      { name: 'Time Management',  icon: '⏱️', useImage: false, level: 'expert'   },
    ],
  },
];

export const levelConfig = {
  expert:       { label: 'Expert',       bars: 5, color: '#0ea5e9' },
  advanced:     { label: 'Advanced',     bars: 4, color: '#10b981' },
  intermediate: { label: 'Intermediate', bars: 3, color: '#f59e0b' },
  familiar:     { label: 'Familiar',     bars: 2, color: '#8b5cf6' },
} as const;